### Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(81)

In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [3]:
model = nn.Linear(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9746]], requires_grad=True), Parameter containing:
tensor([0.5466], requires_grad=True)]


In [4]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 2.963700
Epoch  100/2000 Cost: 0.061942
Epoch  200/2000 Cost: 0.038277
Epoch  300/2000 Cost: 0.023653
Epoch  400/2000 Cost: 0.014616
Epoch  500/2000 Cost: 0.009032
Epoch  600/2000 Cost: 0.005581
Epoch  700/2000 Cost: 0.003449
Epoch  800/2000 Cost: 0.002131
Epoch  900/2000 Cost: 0.001317
Epoch 1000/2000 Cost: 0.000814
Epoch 1100/2000 Cost: 0.000503
Epoch 1200/2000 Cost: 0.000311
Epoch 1300/2000 Cost: 0.000192
Epoch 1400/2000 Cost: 0.000119
Epoch 1500/2000 Cost: 0.000073
Epoch 1600/2000 Cost: 0.000045
Epoch 1700/2000 Cost: 0.000028
Epoch 1800/2000 Cost: 0.000017
Epoch 1900/2000 Cost: 0.000011
Epoch 2000/2000 Cost: 0.000007


In [5]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print("훈련 후 입력이 4일때의 예측값 :", pred_y)

훈련 후 입력이 4일때의 예측값 : tensor([[7.9949]], grad_fn=<AddmmBackward0>)


In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9970]], requires_grad=True), Parameter containing:
tensor([0.0068], requires_grad=True)]


### Multivariable Linear Regression

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(81)

In [8]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [9]:
model = nn.Linear(3, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.5627,  0.3156, -0.2802]], requires_grad=True), Parameter containing:
tensor([-0.4952], requires_grad=True)]


In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 14739.796875
Epoch  100/2000 Cost: 0.689544
Epoch  200/2000 Cost: 0.660872
Epoch  300/2000 Cost: 0.633708
Epoch  400/2000 Cost: 0.607963
Epoch  500/2000 Cost: 0.583551
Epoch  600/2000 Cost: 0.560408
Epoch  700/2000 Cost: 0.538453
Epoch  800/2000 Cost: 0.517611
Epoch  900/2000 Cost: 0.497834
Epoch 1000/2000 Cost: 0.479052
Epoch 1100/2000 Cost: 0.461201
Epoch 1200/2000 Cost: 0.444234
Epoch 1300/2000 Cost: 0.428117
Epoch 1400/2000 Cost: 0.412782
Epoch 1500/2000 Cost: 0.398193
Epoch 1600/2000 Cost: 0.384304
Epoch 1700/2000 Cost: 0.371090
Epoch 1800/2000 Cost: 0.358507
Epoch 1900/2000 Cost: 0.346517
Epoch 2000/2000 Cost: 0.335093


In [11]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.9843]], grad_fn=<AddmmBackward0>)


In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.1031, 0.7329, 0.1909]], requires_grad=True), Parameter containing:
tensor([-0.4901], requires_grad=True)]


### Class Implemention

In [13]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [14]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [15]:
# model = LinearRegressionModel()
# model = MultivariateLinearRegressionModel()

1) Linear Regression

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(81)

In [17]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [18]:
model = LinearRegressionModel()

In [19]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 2.963700
Epoch  100/2000 Cost: 0.061942
Epoch  200/2000 Cost: 0.038277
Epoch  300/2000 Cost: 0.023653
Epoch  400/2000 Cost: 0.014616
Epoch  500/2000 Cost: 0.009032
Epoch  600/2000 Cost: 0.005581
Epoch  700/2000 Cost: 0.003449
Epoch  800/2000 Cost: 0.002131
Epoch  900/2000 Cost: 0.001317
Epoch 1000/2000 Cost: 0.000814
Epoch 1100/2000 Cost: 0.000503
Epoch 1200/2000 Cost: 0.000311
Epoch 1300/2000 Cost: 0.000192
Epoch 1400/2000 Cost: 0.000119
Epoch 1500/2000 Cost: 0.000073
Epoch 1600/2000 Cost: 0.000045
Epoch 1700/2000 Cost: 0.000028
Epoch 1800/2000 Cost: 0.000017
Epoch 1900/2000 Cost: 0.000011
Epoch 2000/2000 Cost: 0.000007


In [20]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print("훈련 후 입력이 4일때의 예측값 :", pred_y)

훈련 후 입력이 4일때의 예측값 : tensor([[7.9949]], grad_fn=<AddmmBackward0>)


2) Multivariable Linear Regression

In [21]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [22]:
model = MultivariateLinearRegressionModel()

In [23]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 40849.699219
Epoch  100/2000 Cost: 22.379032
Epoch  200/2000 Cost: 21.100193
Epoch  300/2000 Cost: 19.901987
Epoch  400/2000 Cost: 18.779015
Epoch  500/2000 Cost: 17.726292
Epoch  600/2000 Cost: 16.739014
Epoch  700/2000 Cost: 15.812906
Epoch  800/2000 Cost: 14.943832
Epoch  900/2000 Cost: 14.128082
Epoch 1000/2000 Cost: 13.362137
Epoch 1100/2000 Cost: 12.642588
Epoch 1200/2000 Cost: 11.966568
Epoch 1300/2000 Cost: 11.331134
Epoch 1400/2000 Cost: 10.733668
Epoch 1500/2000 Cost: 10.171717
Epoch 1600/2000 Cost: 9.642964
Epoch 1700/2000 Cost: 9.145247
Epoch 1800/2000 Cost: 8.676638
Epoch 1900/2000 Cost: 8.235209
Epoch 2000/2000 Cost: 7.819303


In [24]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.4187]], grad_fn=<AddmmBackward0>)
